In [1]:
# PYTHON IMPORTS
import os, copy, math
from tqdm.notebook import trange, tqdm

# IMAGE IMPORTS 
from PIL import Image

# DATA IMPORTS 
import random, h5py, glob
import numpy as np

# PLOTTING
import matplotlib.pyplot as plt
import matplotlib.cm as cm

# SHAPES IMPORTS
import shapely
import geopandas as gpd
from shapely.ops import unary_union
from shapely.geometry import LineString, Polygon, Point

# MY OWN CLASSES
from FindGrid import *

# OCR libraries
import pytesseract
from fuzzywuzzy import fuzz
import re

# INITIALIZE
t_path = r'C:\Users\fhacesga\AppData\Local\Programs\Tesseract-OCR\tesseract.exe'
pytesseract.pytesseract.tesseract_cmd = t_path

# PREFERENCES
Image.MAX_IMAGE_PIXELS = 933120000

C:\Users\fhacesga\Anaconda3\envs\deeplearning\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
data_dir      = r"C:\Users\fhacesga\OneDrive - University Of Houston\AAA_RECTDNN\data/"
prep_folder   = f"{data_dir}TileLocator/in_prepped_v2/"

In [ ]:
# List all files in the directory
for i, filename in enumerate(os.listdir(prep_folder)):
    image_path = os.path.join(prep_folder, filename)
    if image_path.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.tif')):
        
        outdict = FindGrid(image_path)
        if not outdict:
            continue
            
        contour_dict = outdict.copy()
        contours_shapely = {}
        for i, (k, v) in enumerate(contour_dict.items()):
            if isinstance(v, Polygon):
                contours_shapely[k] = v.simplify(tolerance=10)
                continue
            contour_points = [tuple(point[0]) for point in v]
            contours_shapely[k] = Polygon(contour_points).simplify(tolerance=10)
        create_shapefile_from_dict(contours_shapely, f"tempfiles/{i}_{filename[:-4]}.shp")
        

C:\Users\fhacesga\Anaconda3\envs\deeplearning\lib\site-packages\torchvision\models\_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
C:\Users\fhacesga\Anaconda3\envs\deeplearning\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


  0%|          | 0/5 [00:00<?, ?it/s]

C:\Users\fhacesga\Desktop\FIRMsDigitizing\RECTDNN\TileLocator.py:93: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = self.softmax(output)
C:\Users\fhacesga\Desktop\FIRMsDigitizing\RECTDNN\SquareLocator.py:94: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = self.softmax(output)
C:\Users\fhacesga\Desktop\FIRMsDigitizing\RECTDNN\FindGrid.py:317: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  for linestring in linestrings:


  0%|          | 0/262 [00:00<?, ?it/s]

(1, 35, 4)
[[[ 1 -1 -1 -1]
  [32  0  2 -1]
  [ 3 -1 -1  1]
  [ 4  2 -1  1]
  [ 5  3 -1  1]
  [ 6  4 -1  1]
  [ 7  5 -1  1]
  [ 8  6 -1  1]
  [ 9  7 -1  1]
  [10  8 -1  1]
  [11  9 -1  1]
  [12 10 -1  1]
  [13 11 -1  1]
  [14 12 -1  1]
  [15 13 -1  1]
  [16 14 -1  1]
  [17 15 -1  1]
  [18 16 -1  1]
  [19 17 -1  1]
  [20 18 -1  1]
  [21 19 -1  1]
  [22 20 -1  1]
  [23 21 -1  1]
  [24 22 -1  1]
  [25 23 -1  1]
  [26 24 -1  1]
  [27 25 -1  1]
  [28 26 -1  1]
  [29 27 -1  1]
  [30 28 -1  1]
  [31 29 -1  1]
  [-1 30 -1  1]
  [33  1 -1 -1]
  [34 32 -1 -1]
  [-1 33 -1 -1]]]
Highest Hierarchy: 1


  0%|          | 0/35 [00:00<?, ?it/s]

In [ ]:
outdict